name: Build Cyberiada Release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  linux-windows-build:
    runs-on: ubuntu-latest # You can change this to macOS or Windows if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: cyberiada

      - name: Download a file
        run: |
          wget https://github.com/avrdudes/avrdude/releases/download/v7.2/avrdude-v7.2-windows-x86.zip -O resources/modules/win32/avrdude.zip
          unzip resources/modules/win32/avrdude.zip -d resources/modules/win32
          rm -f resources/modules/win32/avrdude.zip

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: electronuserland/builder:wine
          options: -v ${{ github.workspace }}:/project
          run: |
            dist/*.deb
            dist/*.snap
            dist/*.AppImage
            dist/*.exe

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: |
            dist/*.deb
            dist/*.snap
            dist/*.AppImage
            dist/*.exe

  mac-build:
    runs-on: 'macos-latest'

    needs: linux-windows-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: cyberiada

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm run bundle:mac

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: |
            dist/*.dmg
